### ISSUE TITLE
having issue with WiFi Relay and the app

### ISSUE THREAD

**Issue by shahram7** [tomasbedrich/home-assistant-skydance#10]
Hi there, I didn't have a chance to work with your integration, because I have problems with the relay selbst and I am not sure in which community I can look for help.
My landlord has installed these led dimmers with remote control and I've purchased the WiFi Relay from China. The app isn't available for my samsung galaxy s21 fe in play store.
I've downloaded and installed the app from evozi.

my main problem is that the relay doesn't stay in network. it got kicked out every time.
when I give the password of my ssid I see the led turns to blue but after 3 4 minutes it turns green again and I am not able to do any thing in app.

have you had same issues with your WiFi Relay?

Best Regards, Shahram

**Comment by tomasbedrich** [comment]
Hello, I had some problems with the relay as well.  It didn't work properly when there were spaces in the SSID name or in the password. Try to change these parameters of your Wifi network (maybe also encryption) and you will see if some of it fixes it.

**Comment by shahram7** [comment]
Hi @tomasbedrich, thanks for your reply, but I don't have a space in my SSID or password and the encryption is set to WPA2(CCMP)

**Comment by tomasbedrich** [comment]
Sorry to say, but I don't have a better advice for you. If you figure out what is wrong, please share it here so that others can learn.

BTW I ended up buying Zigbee controllers for my LED strips. They are much more reliable, including state report feature etc. This is what I use: https://miboxer.com/product/5-in-1-led-strip-controller-zigbee-3-0-2-4g
